// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRvppc5YB8Wu5OShM2jDI4A4W-akYdrg',
    appId: '1:926488724233:web:db5cbb79d9498956b289d8',
    messagingSenderId: '926488724233',
    projectId: 'paymentsystem-1f3ae',
    authDomain: 'paymentsystem-1f3ae.firebaseapp.com',
    storageBucket: 'paymentsystem-1f3ae.firebasestorage.app',
    measurementId: 'G-JRM8SLZM2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlZ64i1IdCVR6vnlQkodbFUEu5vdZFqc',
    appId: '1:926488724233:android:322e9abfa1474254b289d8',
    messagingSenderId: '926488724233',
    projectId: 'paymentsystem-1f3ae',
    storageBucket: 'paymentsystem-1f3ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVYm3sYbpDS64h42G_6RtFGsJIP16Tvk',
    appId: '1:926488724233:ios:b5290b955a0d111ab289d8',
    messagingSenderId: '926488724233',
    projectId: 'paymentsystem-1f3ae',
    storageBucket: 'paymentsystem-1f3ae.firebasestorage.app',
    iosBundleId: 'com.example.lamuSalaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVYm3sYbpDS64h42G_6RtFGsJIP16Tvk',
    appId: '1:926488724233:ios:b5290b955a0d111ab289d8',
    messagingSenderId: '926488724233',
    projectId: 'paymentsystem-1f3ae',
    storageBucket: 'paymentsystem-1f3ae.firebasestorage.app',
    iosBundleId: 'com.example.lamuSalaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuRvppc5YB8Wu5OShM2jDI4A4W-akYdrg',
    appId: '1:926488724233:web:4220460d352fa5d9b289d8',
    messagingSenderId: '926488724233',
    projectId: 'paymentsystem-1f3ae',
    authDomain: 'paymentsystem-1f3ae.firebaseapp.com',
    storageBucket: 'paymentsystem-1f3ae.firebasestorage.app',
    measurementId: 'G-G1W3TRXRMV',
  );
}
